### ISSUE TITLE
invalid \x escape

### ISSUE THREAD

**Issue by revad** [oneyoung/python-ipernity-api#1]
I followed the tutorial. No problems with authorisation. 
But when I did "upload a doc":

```
Traceback (most recent call last):
  File "iploadr.py", line 56, in <module>
    Upload.file(file="///home/david/projects/python/ipernity/iploadr/imagedir/img_4583.jpg", title='Test 1 jpg')
  File "/usr/lib/python2.7/site-packages/ipernity_api/reflection.py", line 105, in wrapper
resp = request(**params)
  File "/usr/lib/python2.7/site-packages/ipernity_api/rest.py", line 105, in call_api
raise IpernityError(str(e))
ipernity_api.errors.IpernityError: invalid \x escape
```

If I look at the image jpg file with a hex editor I see many occurrences of string '\X' so I wonder whether it is the image file itself that is generating the error. So I shrink the image:
convert -resize 200 img_4583.jpg img_4583_s.jpg
I check that the smaller image file contains no occurrences of '\X' and try again.

It works! But it generates a doc which is not viewable in ipernity and appears under docs not photos:
http://www.ipernity.com/doc/919331/33912305

So, 2 issues:
1 How to avoid 'invalid \x escape'?
2 Why is the doc not viewable?

Dave (UK)

**Comment by oneyoung** [comment]
Hi Dave,

Could you attach your jpeg file which contains '\X', and also the re-sized image for further checking?

Thanks.

**Comment by revad** [comment]
![img_4583](https://cloud.githubusercontent.com/assets/3061165/3634841/497188e4-0f4c-11e4-804f-3ff3c72f8ef5.jpg)
![img_4583_s](https://cloud.githubusercontent.com/assets/3061165/3634844/5fc4ed0c-0f4c-11e4-830b-bf7c95f8a9b1.jpg)

**Comment by oneyoung** [comment]
Hi Dave,

Thanks for your feedback.
This issue has been fixed in [this commit](https://github.com/oneyoung/python-ipernity-api/commit/95fcbf73610a3c05de6cb8c37d456ee94455635a).
You can also fetch the latest version (v0.12) of [ipernity_api from pypi](https://pypi.python.org/pypi/ipernity_api/0.12).

**Comment by revad** [comment]
That works - thank you.
And I see that I can add description and permission parameters too - presumably any of the parameters of 'upload.file':
http://www.ipernity.com/doc/919331
It's very easy to use. Thanks for writing it!
Dave
