### ISSUE TITLE
Error importing set_auth_handler (Android, py4a, python 2.6)

### ISSUE THREAD

**Issue by revad** [oneyoung/python-ipernity-api#2]
My program works on Linux with python 2.7 On Android (sl4a/py4a) I get the error shown in the screenshot. 

py4a uses python 2.6.  - is that the problem?

![screenshot_ipernity_api_py4a_error](https://cloud.githubusercontent.com/assets/3061165/3646925/bec5c706-10f8-11e4-9cd6-092500dd380a.png)

**Comment by oneyoung** [comment]
It seems that Python 2.6 and earlier can't use dict comprehension like this way:

``` python
d = {key: value for (key, value) in iterable}
```

(http://stackoverflow.com/questions/1747817/python-create-a-dictionary-with-list-comprehension)

I might need to find a way to workaround it.

**Comment by oneyoung** [comment]
Fixed in [c5ce99d](https://github.com/oneyoung/python-ipernity-api/commit/c5ce99d9aca736c1263f4f3c1b8daaa3c6014372).

All test cases pass under Python 2.6
