### ISSUE TITLE
Error 'keywords must be strings' (Android, py4a, python 2.6.2)

### ISSUE THREAD

**Issue by revad** [oneyoung/python-ipernity-api#3]
Another Python 2.6 issue:
![screenshot_ipernity_api_keywords_error](https://cloud.githubusercontent.com/assets/3061165/3658512/9dcf3990-11a4-11e4-9422-47efdf13e846.png)

Googling suggests this might be a bug in Python 2.6.2 with unicode keywords. I have the latest release of Py4A (r5) which is Python 2.6.2. But if there is not a simple fix or workround to this I could probably move the application to QPython which uses 2.7. I don't want you to expend a lot of effort supporting an ancient version of Python!

Dave

**Comment by oneyoung** [comment]
It's a sad news that Python 2.6.2 can't support unicode keywords.

In python_ipernity_api, it uses a lot of unicode keywords, so there would not be a neat and quick fix for this issue.
I would like to update python version support to 2.6.5+.

Of course, if you come up with a better solution, patch is always welcomed.

**Comment by revad** [comment]
OK.  There are some unofficial releases of 2.7 for SL4A which I may be able to install, and if not there is QPython. 
Dave
